Minor documentation fixes
buildingSMART/foundation-API pull request #12
Opened 2020-11-23 15:45 UTC by leosobral

2020-11-23 19:10 UTC, jasollien approved these changes

2020-11-23 19:10 UTC, jasollien requested changes
Needs to be based on release_2_2

2020-11-23 19:11 UTC, jasollien commented
> Needs to be based on release_2_2

Never mind. Master is the only branch :)

2020-11-24 09:43 UTC, ykulbak approved these changes

2020-11-24 09:43 UTC, merged